sudo: required
services:
  - docker

before_install:
  - docker build -t nobscs/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nobscs/react-test npm test

after_success:
  - docker build -t nobscs/multi-client ./client
  - docker build -t nobscs/multi-nginx ./nginx
  - docker build -t nobscs/multi-server ./server
  - docker build -t nobscs/multi-worker ./worker

#Login to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Take those images and push them to docker hub
  - docker push nobscs/multi-client
  - docker push nobscs/multi-server
  - docker push nobscs/multi-worker
  - docker push nobscs/multi-nginx

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-123391336772
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_acceess_key: $AWS_SECRET_KEY
